name: daily-cron

on:
  schedule:
    - cron: '20 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call our API route
        run: |
          curl --request POST \
          --url 'https://financa-api-jefferson00.vercel.app/invoices/verify' \

